[제로] 1주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #12
Opened 2022-06-30 03:33 UTC by asebn1

감사합니다~

2022-06-30 14:41 UTC, summerlunaa requested changes
제로 안녕하세요 파랑이에요~
몇 안 되는 파이썬 동지라 반갑네요.
간단하게 리뷰 남겨봤습니다! 반영해주세요ㅎㅎ😇

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/10814/10814_python_제로.py
> +lst = []
`lst` 말고 좀 더 적절한 변수명을 사용하는 건 어떨까요?

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/10814/10814_python_제로.py
> +    lst.append((int(age), name))
리스트 안에 for 문을 넣을 수도 있습니다!

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/10814/10814_python_제로.py
> +    print(lst[i][0], lst[i][1])
인덱스 대신 바로 원소를 꺼내 쓸 수도 있을 것 같아여 
```suggestion
for user in lst:
    print(user[0], user[1])
```

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/14659/14659_python_제로.py
> +    answer = max(answer, cnt)
굳굳 💯

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/17362/17362_python_제로.py
> +# 3
2인데 오타났어요~

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/17362/17362_python_제로.py
> +    answer = 4
이렇게 if else 문으로 5가지 케이스를 나눠 풀 수도 있군요..! 새로운 방법 배워갑니다

2022-06-30 14:41 UTC, summerlunaa commented on 1주차/4796/4796_python_제로.py
> +        step2 = L
`min` 메서드를 사용해서 간단하게 줄여볼 수 있겠네요
```suggestion
    step2 = min(L, step2)
```

2022-07-01 23:12 UTC, asebn1 commented on 1주차/10814/10814_python_제로.py
> +lst = []
ㅠㅠ... 코파랑 날카롭네요;

2022-07-01 23:13 UTC, asebn1 commented on 1주차/10814/10814_python_제로.py
> +    print(lst[i][0], lst[i][1])
킹정합니다

2022-07-01 23:15 UTC, asebn1 commented on 1주차/4796/4796_python_제로.py
> +        step2 = L
굳

2022-07-02 02:11 UTC, summerlunaa approved these changes

2022-07-04 06:32 UTC, pup-paw approved these changes
안녕해세요 제로! 야호입니다 :)
죄송하게도 제가 알고리즘 문제를 얼마 풀어보지 못한 초심자라... 날카로운 피드백을 못드린 것 같네용 ㅠ0ㅠ
제로의 풀이를 보며 오히려 제가 많이 배운 것 같아요..! 하루 빨리 성장해서 좋은 리뷰 남길 수 있도록 하겠습니다 :)
문제 푸시느라 수고하셨어요~~

2022-07-04 06:32 UTC, pup-paw commented on 1주차/14659/14659_python_제로.py
> +    answer = max(answer, cnt)
오.. 좋은 풀이네요 배우고 갑니다!! 🤓

2022-07-04 06:32 UTC, pup-paw commented on 1주차/17362/17362_python_제로.py
> +elif n%4 == 3:
4로 나누는 아이디어 넘 좋네용! 또 하나 배우고 갑니다...ㅎ

2022-07-04 07:32 UTC, merged