[레오] 4주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #128
Opened 2022-07-23 08:47 UTC by DWL21

21938 런타임에러 ValueError가 뜨네요.

2022-07-23 13:51 UTC, kth990303 requested changes
간단한 코멘트 남겼어요! 해결해보시고, 다른 문제들도 한 번 도전해보세요~

2022-07-23 13:51 UTC, kth990303 commented on 4주차/21938/21938-python-leo.py
> +        pop(i, j - 1)
현재 N이 가로, M을 세로로 입력받으셨는데, i, j가 의도하신대로 전달되는게 맞을까요?

2022-07-23 13:51 UTC, kth990303 commented on 4주차/21938/21938-python-leo.py
> +            if display[j][index] + display[j][index + 1] + display[j][index + 2] >= T:
나눗셈 연산으로 인한 오차 없이 곱셈연산으로 잘해주셨어요! 😄

2022-07-24 07:07 UTC, DWL21 commented on 4주차/21938/21938-python-leo.py
> +        pop(i, j - 1)
넵 잘못 들어갔네요. 수정하였습니다.

2022-07-24 07:08 UTC, DWL21 commented
통과하게 수정하였습니다!

2022-07-24 14:19 UTC, kth990303 approved these changes
수정 잘해주셨어요~ 다른 문제들도 해결해보시면 좋을 것 같습니다!

2022-07-25 10:25 UTC, sinb57 approved these changes
Discussion에 올리신 문제 해결하셨네요!! 시간될 때 다른 문제들도 시도해보시면 좋겠습니다~!ㅎㅎ

2022-07-26 01:16 UTC, merged