[후디] 4주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #147
Opened 2022-07-23 14:51 UTC by devHudi

RecursionError가 계속 뜨네요 ㅠ,ㅠ 어디서 무한루프에 빠진지 잘 모르겠습니다 🥲

2022-07-24 06:48 UTC, asebn1 requested changes
후디 고생하셨습니다! 
저도 원인을 찾지 못했는데 반례하나는 찾았습니다...ㅎ
2차원 배열에서 바로 dfs나 bfs를 적용해서 푸시는건 어떨까요??
잘 수정해주시리라 믿고 approve하겠습니다!

2022-07-24 06:48 UTC, asebn1 commented on 4주차/21938/21938_후디_python.py
> +        new_rgb.append(num > T)
1차원으로 나누신 이유가 있으신가요?

2022-07-24 06:48 UTC, asebn1 commented on 4주차/21938/21938_후디_python.py
> +        graph[i].append(i + M)
제가 완벽하게 이해한 건 아니지만 반례가 있어요
```java
1 1
255 255 255
101
```
넣으면 1이 나와야 하는데 0이 나옵니다!

2022-07-24 06:48 UTC, asebn1 approved these changes

2022-07-25 03:50 UTC, tonic523 approved these changes
후디 알고리즘 푸느라 고생하셨어요!
제가 이 문제만 아직 풀지 못해 제대로 된 리뷰는 못드려서 죄송해요 ㅠㅠ
우선 approve 드리고 문제 풀이 이후에 다시 문제를 보고 피드백 드리겠습니다!

2022-07-25 12:29 UTC, devHudi commented on 4주차/21938/21938_후디_python.py
> +        new_rgb.append(num > T)
하하... 문제가 어려워서 일단 동작하는 대로 만들다보니 이런코드가 나와버렸네요..

2022-07-25 12:30 UTC, devHudi commented on 4주차/21938/21938_후디_python.py
> +        graph[i].append(i + M)
헉,, 반례까지 찾아주시다니 너무 감사드립니다 ㅠㅠ 코멘트 참고해서 다시 풀어보겠습니다!!! 감사해요!!

2022-07-26 01:07 UTC, merged