[필즈] 4주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #148
Opened 2022-07-23 14:54 UTC by progress0407

푼 것은 `pass`, 
풀지 못한 것은`fail` 이라고 표기했습니다.. ㅎㅎ

~지금 자정 직전인데 한 문제도 못풀었네요 흐흫ㅠㅠㅠ~

2022-07-24 07:13 UTC, kth990303 requested changes
필즈 수고하셨어요!
두 문제 모두 Fail이어서 Changes Request 남겨드렸어요~
코멘트 남겼는데 반영해보시고, 혹시나 너무 어려우면 디스커션이나 단톡에 질문으로 남겨주시면 확인해드릴게요!

2022-07-24 07:13 UTC, kth990303 commented on 4주차/16198/16198_java_필즈.java
> +        final Reader reader = new InputStreamReader(System.in);
아예 한 번에 BufferedReader로 받아도 될 것 같아요!
```java
final BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
```

2022-07-24 07:13 UTC, kth990303 commented on 4주차/16198/16198_java_필즈.java
> +    }
이 exception catch 부분은 알고리즘에서는 크게 필요없는 부분이에요!
메서드 분리하지 않으셔도 괜찮을 것 같아요.

- 알고리즘 문제들은 입력이 올바르게 주어짐이 보장되며, 온라인 채점 사이트의 컴파일러에서 입출력을 담당하기 때문에 해당 코드에서 buffer 관련 예외처리를 해줄 필요가 없음.

2022-07-24 07:13 UTC, kth990303 commented on 4주차/16198/16198_java_필즈.java
> +    }
이 메서드 없이 List의 `remove`, `add` 작업으로 처리해보는 것도 연습해보면 좋을 것 같아요.
코드가 훨씬 짧아질거예요~

2022-07-24 07:13 UTC, kth990303 commented on 4주차/21938/21938_java_필즈.java
> +        final int[][] rgb_arr = new int[H][W];
입력이 총 H * W * 3개 주어지는데, 정말 배열크기를 int[H][W]로만 잡아도 충분할까요?

2022-07-24 07:13 UTC, kth990303 commented on 4주차/21938/21938_java_필즈.java
> +                final int b = parseInt(rgb_line[W * w + 2]);
잘 처리해주셨네요! 👍

2022-07-24 07:13 UTC, kth990303 commented on 4주차/21938/21938_java_필즈.java
> +                }
만약 이 처리를 안한다면 어떻게 될까요?

2022-07-24 07:13 UTC, kth990303 commented on 4주차/21938/21938_java_필즈.java
> +                visited[h_iter][w_iter] = true;
80~103번째 줄에서 visited 방문체크처리를 해주는데, 여기서 중복해서 해준 이유가 있을까요?

2022-07-24 07:13 UTC, kth990303 commented on 4주차/21938/21938_java_필즈.java
> +                        }
매번 T 이상임을 확인하고 있네요! BFS를 돌리기 전에 미리 전처리해주는 건 어떨까요?

ex. 
```
255 255 255 100 100 100 255 255 255
100 100 100 255 255 255 100 100 100
255 255 255 100 100 100 255 255 255
T: 101
```
->
```
1 0 1
0 1 0
1 0 1
```
-> 이후에 BFS 돌기!

2022-07-25 07:04 UTC, yxxnghwan approved these changes
안녕하세요 필즈! 간단한 피드백만 남겼는데, 답 내주시고 코드 반영시켜주시면 좋을 것 같아요! 사소한 문제라 approve할게요!

2022-07-25 07:04 UTC, yxxnghwan commented on 4주차/21938/21938_java_필즈.java
> +         */
메서드로 분리해서 네이밍 해주시면 불필요한 주석도 제거되고 더 클린코드가 될 것 같네요!

2022-07-25 12:41 UTC, progress0407 commented on 4주차/21938/21938_java_필즈.java
> +         */
ㅎㅎㅎ... 그런 것 같아요! 감사합니다

2022-07-25 12:41 UTC, progress0407 commented on 4주차/21938/21938_java_필즈.java
> +                        }
아하!! 아예 `1, 0`으로 나누는 것도 좋을 것 같아요! ㅎㅎ

2022-07-25 12:42 UTC, progress0407 commented on 4주차/16198/16198_java_필즈.java
> +    }
맞아요~!!

배열을 이어 붙이는 로직입니다 ㅎ

```java
[1,2] + [3,4]
= [1,2,3,4]
```

2022-07-25 12:51 UTC, progress0407 commented on 4주차/16198/16198_java_필즈.java
> +            }
아하!... 현재는 수정본으로 해당 라인이 변경되어있어요!
(다만 커밋은 안했네요 ㅠ)

ㅎㅎ 케이가 제대로 본 것이 맞습니다 !

2022-07-25 13:04 UTC, progress0407 commented on 4주차/16198/16198_java_필즈.java
> +            }
오 ㅎㅎ 맞아요!
max 값에 대한 처리만..해서 오답을 냈었던 기억이 있네요 ㅎㅎ

예시 코드 감사합니다 !

2022-07-25 13:05 UTC, progress0407 commented on 4주차/21938/21938_java_필즈.java
> +                final int b = parseInt(rgb_line[W * w + 2]);
ㅎㅎ

2022-07-25 13:07 UTC, progress0407 commented on 4주차/16198/16198_java_필즈.java
> +    }
아 ㅎㅎ 그렇군요 !! 감사합니다..ㅎㅎ

다만 main 코드에 저 부분이 있는 것이... 우테코에서 길들여진 습관상 석연치 않아서 저렇게 썼는데.. 이부분은 케이가 지목한 점을 알고 있되, 굳이 없애지는 않을게요 ㅎ

2022-07-25 13:13 UTC, progress0407 commented on 4주차/21938/21938_java_필즈.java
> +        final int[][] rgb_arr = new int[H][W];
앗.. 혹여나 했지만 아마 해당 부분은 아닌 걸로 보입니다.. ㅠ

H * (W*3) 이 입력인 것은 맞지만

rgb_arr 에는 rgb의 평균만이 들어가기 때문에
H * W 만 들어가거든요 ㅠ

2022-07-25 13:15 UTC, progress0407 commented on 4주차/21938/21938_java_필즈.java
> +                visited[h_iter][w_iter] = true;
음.. 당시에는 저부분을 리펙터링하지 않고 했었던 것 같아요.

저부분을 x/y 변화량으로 리펙터링하는 방법도 있을 것 같네요!

2022-07-25 13:40 UTC, progress0407 commented
케이~! 조언 고마워요 ㅎ
제가 다 소화는 못했지만,

RGB 문제는 금주 평일에 다시 반영하도록 노력해볼게요! ㅎㅎ

2022-07-25 14:07 UTC, kth990303 commented on 4주차/16198/16198_java_필즈.java
> +    }
저는 remove, add를 안써서 아마 다른 크루들의 코드를 참고하면 좋을거예요! 제 코드는 링크드리스트 비스무리하게 돼있답니다 ㅎㅎ 참고하셔도 좋아요!

2022-07-25 14:08 UTC, kth990303 approved these changes
코멘트 확인하시고 고민해보신 것 같아 approve하겠습니다~!

2022-07-26 01:06 UTC, merged