[아서] 5주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #175
Opened 2022-07-30 13:19 UTC by Hyunta

알고리즘에 신경을 많이 못썼네요
우선 2문제 풀고 시간되는데로 풀어서 올려보겠습니다.

2022-07-31 03:44 UTC, sinb57 requested changes
안녕하세요 아서!! 20922번 풀이 코드 잘못 올리신거 같아요!! 확인부탁드려요~ㅎ

2022-07-31 07:02 UTC, Hyunta commented
@sinb57 앗,,, 내용이 누락됐네요 수정해서 다시 올렸습니다!

2022-07-31 08:17 UTC, sinb57 approved these changes
확인했습니다~ 로직이 간단하네요!! 잘봤습니다ㅎ

2022-08-01 14:44 UTC, Juhyung990122 approved these changes
안녕하세요 아서! 고생 많으셨습니다ㅎㅎ 잘봤어요~~

2022-08-02 00:20 UTC, merged