[알렉스] 1주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #24
Opened 2022-07-02 06:06 UTC by yxxnghwan

잘 부탁드립니다!🤗
코테 준비 처음 하는데 생각보다 쉽지가 않네요😂

2022-07-02 09:29 UTC, ulimy requested changes
안녕하세요 알렉스! 아리입니다^~^
알고리즘이 처음이라고 하셨는데 정말 잘해주신 것 같아요!
다만 작은 바램이 있다면, 우테코에서 지향하는 클린코드 등과 코딩테스트를 조금 다른 방향으로 바라봐주셨으면 좋겠어요. 잘못된 입력에 대한 고려, 상수분리, 원시값 포장 등등의 것들 보다는 입력, 출력, 수행시간 등을 더욱 중요하게 바라봐주신다면 훨씬 수월한 코딩테스트 준비가 될 것이라 예상합니다!

2022-07-02 09:29 UTC, ulimy commented on 1주차/17362/Java_17362_이영환.java
> +            return fingerNumberCycle.get(value % CYCLE_LENGTH);
list로 선언해두고 나머지값을 인덱스로 활용하다니 너무 좋네요!

2022-07-02 09:29 UTC, ulimy commented on 1주차/10814/Java_10814_이영환.java
> +            final String[] rawMemberInput = scanner.nextLine().split("\\s+");
Scanner는 조금 느려서 코딩테스트에서는 BufferedReader를 많이 사용한다고 해요!

2022-07-02 09:29 UTC, ulimy commented on 1주차/10814/Java_10814_이영환.java
> +                throw new IllegalArgumentException("가입자 수 입력 오류! memberCount = " + value);
코딩테스트에서는 잘못된 입력이 들어오는 일이 거의 없다고 알고있어요! 고려하지 않아도 괜찮습니다 :)

2022-07-02 09:29 UTC, ulimy commented on 1주차/10814/Java_10814_이영환.java
> +                .sorted(Comparator.comparingInt(Member::getAge))
Comparator의 comparingInt를 활용하신게 너무 좋네요!

2022-07-03 06:16 UTC, RunaNam approved these changes
안녕하세요 알렉스! 루나입니다 :)
전반적으로 딱히 크게 문제될 부분은 없어서 바로 Approve 드렸습니다. 👍
다만, 아리가 말씀해주신 것 처럼 알고리즘 풀이에 있어서는 우테코에서 저희가 지향하는 바와는 조금 다른 방향에서 '시간 안에 가장 효율적인 코드' 를 짠다는 느낌에서 수행 시간같은 부분에 조금 더 초점을 두어서 진행해주시는 편이 조금 더 도움이 될 것 같네요.

2022-07-03 06:16 UTC, RunaNam commented on 1주차/4796/Java_4796_이영환.java
> +            final String[] lpv = rawLpv.split("\\s+");
split 함수에서 조건을 조금 더 넓게 주시려고 "\\s+"로 옵션을 주신 것 같아요! 그렇지만 이 문제에서는 간단하게 " " (공백) 으로 두셔도 되지 않을까 싶습니다. 저같은 경우에는 늘 헷갈려서 그냥 주어진 부분에서 직관적으로 생각하는 편이라 이렇게 하는 걸수도 있지만요 ㅎㅎ

2022-07-04 08:47 UTC, ulimy approved these changes
1주차 고생많으셨습니다! 앞으로 함께 화이팅 해용^~^

2022-07-04 16:56 UTC, merged