[야호] 1주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #29
Opened 2022-07-02 09:50 UTC by pup-paw

쿼리치, 이프 잘 부탁드립니다❗️

2022-07-02 13:26 UTC, meatsby requested changes
안녕하세요 야호~ 쿼리치입니다!
생각해보면 좋을 것 같은 부분들 몇가지 리뷰해놨으니 간단히 확인 부탁드려요 😁

2022-07-02 13:26 UTC, meatsby commented on 1주차/14659/14659_python_yaho.py
> +print(tmp)
이 문제는 다시 확인해보셔야할 것 같아요!

2022-07-02 13:37 UTC, summerlunaa requested changes
야호 안녕하세요 파랑입니다~~
몇 가지 코멘트 남겼으니 확인부탁드립니다😁👍

2022-07-02 13:37 UTC, summerlunaa commented on 1주차/14659/14659_python_yaho.py
> +    for j in range(i+1, n):
이중 for문을 사용하지 않고 O(N)으로 문제를 해결할 수도 있습니다!! 한 번 고민해보면 좋을 것 같아요ㅎㅎ

2022-07-02 13:37 UTC, summerlunaa commented on 1주차/14659/14659_python_yaho.py
> +tmp = 0
개인적으로는 결과가 담기는 변수니까 tmp 말고 다른 이름을 사용하는 게 더 좋을 것 같아요!

2022-07-02 13:37 UTC, summerlunaa commented on 1주차/4796/4796_python_yaho.py
> +    if l+p+v == 0:
값이 음수인 경우는 없지만 `l==p==v==0 `으로 명확하게 검증해주는 게 좋지 않을까요?

2022-07-09 09:47 UTC, pup-paw commented on 1주차/4796/4796_python_yaho.py
> +import sys
오오 좋은 방법인 것 같아요!

2022-07-09 09:47 UTC, pup-paw commented on 1주차/10814/10814_python_yaho.py
> +members.sort(key=itemgetter(0))
오 한줄로 줄일 수 있겠네요 :)

2022-07-09 09:52 UTC, pup-paw commented on 1주차/4796/4796_python_yaho.py
> +    if l+p+v == 0:
좋은 것 같습니당!!

2022-07-09 10:18 UTC, closed without merging