[후디] 1주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #31
Opened 2022-07-02 09:59 UTC by devHudi

알고리즘 왕 초보입니다 😂 잘부탁드려요!

2022-07-02 12:28 UTC, bugoverdose reviewed
안녕하세요. 리뷰어는 아니고 관람객입니다.

지나갑니다.

2022-07-02 12:28 UTC, bugoverdose commented on 1주차/14659/14659_python_후디.py
> +
TIP: 저의 경우 저 부분은 생략해요. 디폴트가 `" "`라서요

```suggestion
attackers = list(map(int, input().split()))
```

2022-07-02 12:28 UTC, bugoverdose commented on 1주차/10814/10814_python_후디.py
> +    user = input().split(" ")
지금처럼 `input()`의 호출 회수가 입력되는 데이터의 개수(n)에 비례하여 증가하는 경우, `input()` 대신 `sys.stdin.readline()`을 사용하는건 어떨까요? 성능 개선을 습관화하면 좋은 것 같아서요.

```python
import sys

# input을 성능이 더 좋은 메서드로 덮어써서 사용. 
# 그 이후 코드는 동일하게 작성 가능.
input = sys.stdin.readline 
```

2022-07-02 15:10 UTC, DWL21 requested changes
안녕하세요~ 리뷰 남기고 수정 요청 드립니다.

2022-07-02 15:10 UTC, DWL21 commented on 1주차/4796/4796_python_후디.py
> +    l, p, v = case
```suggestion
    l, p, v = list(map(int, input().split(" ")))
    if not l + p + v:
        break
```
아래서 case를 다시 할당하기보다 미리 할당하는 것도 괜찮아 보이네요.
추가로 l, p, v가 모두 양수이므로 이렇게 조건문을 작성할 수도 있어요!

2022-07-02 15:10 UTC, DWL21 commented on 1주차/4796/4796_python_후디.py
> +    day = v // p * l + min(l, v - v // p * p)
```suggestion
    day = v // p * l + min(l, v - (v // p) * p)
```
v - v를 보고 멈칫했네요ㅎㅎ.  연산자 우선 순위가 있지만 이런 경우에 괄호로 구분해주면 가독성이 나아질 수 있겠죠?

2022-07-02 15:10 UTC, DWL21 commented on 1주차/4796/4796_python_후디.py
> +    print(f"Case {index + 1}: {day}")
f-string이라 읽기 편하네요.

2022-07-03 08:10 UTC, devHudi commented on 1주차/14659/14659_python_후디.py
> +
아! 오랜만에 파이썬을 잡으니 디폴트 값을 잊었네요 ㅎㅎ! 감사합니다 👍

2022-07-03 08:11 UTC, devHudi commented on 1주차/10814/10814_python_후디.py
> +    user = input().split(" ")
애초에 `input()` 대신 `sys.stdin.readline` 을 사용하는 버릇을 들이는것이 좋겠네요! 꿀팁 감사합니다

2022-07-03 08:12 UTC, devHudi commented on 1주차/10814/10814_python_후디.py
> +    user = input().split(" ")
잊고 있었는데 감사합니다 😄

2022-07-03 08:18 UTC, devHudi commented on 1주차/14659/14659_python_후디.py
> +print(max_kill_count)
좋네요! 감사합니다 👍

2022-07-03 08:20 UTC, devHudi commented on 1주차/4796/4796_python_후디.py
> +    l, p, v = case
l, p, v 를 미리 할당하고, 합을 통해 조건식을 작성하니 확실히 더 보기 좋은 코드가 됐네요 😄

2022-07-03 08:21 UTC, devHudi commented on 1주차/4796/4796_python_후디.py
> +    day = v // p * l + min(l, v - v // p * p)
실제 코딩테스트를 생각했을때 당황하지 않도록 이런 가독성 챙겨주는 것 꼭 필요하겠네요 👍

2022-07-03 08:25 UTC, devHudi commented on 1주차/4796/4796_python_후디.py
> +    print(f"Case {index + 1}: {day}")
확실히 fstring 이 편한 것 같아요 😄

2022-07-04 02:08 UTC, Hyunta approved these changes
위에 두분이 좋은 커멘트를 남겨주셔서 추가로 남길건 없네요ㅎㅎ
고생하셨습니다!

2022-07-04 02:08 UTC, Hyunta commented on 1주차/17362/17362_python_후디.py
> +l = [1, 2, 3, 4, 5, 4, 3, 2]
저랑 비슷하게 푸셨네요ㅎㅎ
아이디어 좋습니다!

2022-07-04 03:28 UTC, DWL21 approved these changes
피드백 반영 확인했습니다.

2022-07-04 09:11 UTC, devHudi commented on 1주차/17362/17362_python_후디.py
> +l = [1, 2, 3, 4, 5, 4, 3, 2]
피드백 감사합니다 ㅎㅎ

2022-07-04 16:58 UTC, merged