[제로] 2주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #46
Opened 2022-07-07 18:06 UTC by asebn1

잘부탁드립니다 :)

2022-07-08 01:44 UTC, kth990303 approved these changes
어려울텐데 수고 많으셨습니다!!
특히 RPG 마스터를 제가 원하는 방법대로 바로 푸신게 인상깊었어요 😄

2022-07-08 01:44 UTC, kth990303 commented on 2주차/11866/11866_python_제로.py
> +visited[current] = True
`visited` 변수를 활용해서 수학적으로 잘 풀었네요!
저는 `queue`를 이용해서 했어요.

2022-07-08 01:44 UTC, kth990303 commented on 2주차/12789/11866_python_제로.py
> +current = 1  # 시작 번호
파일 문제번호가 잘못돼있네요. `12789번`이군요!

2022-07-08 01:44 UTC, kth990303 commented on 2주차/2121/2121_python_제로.py
> +lst = set(lst)
👍 
set (hashset)
- insert: O(logN)
- find: O(logN)

map
- insert: O(1)
- find: O(N)

2022-07-08 01:44 UTC, kth990303 commented on 2주차/22941/22941_python_제로.py
> +    # 몫을 통해 처음 한번 빼고 시작
이게 제일 안전한 방법 같아요. 별도로 나머지까지 case_work하면 복잡해지더라구요 👍

2022-07-08 01:44 UTC, kth990303 commented on 2주차/23827/23827_python_제로.py
> +reverseLst = lst[::-1]
네이밍은 웬만해선 코멘트 안다는 편인데, 조금 헷갈려서 질문드려요.
`reverseLst` 라서 거꾸로 된 배열인 줄 알았는데, 그게 아니더라구요. 혹시 네이밍 이유를 여쭤봐도 될까요??

2022-07-08 01:46 UTC, asebn1 commented on 2주차/2121/2121_python_제로.py
> +lst = set(lst)
케이짱짱맨

2022-07-08 03:04 UTC, asebn1 commented on 2주차/23827/23827_python_제로.py
> +reverseLst = lst[::-1]
거꾸로 된 배열로 작성한 거 맞아요!

2022-07-11 06:47 UTC, DWL21 requested changes
제로 안녕하세요~ 코드 스타일에서 개선해 볼 만한 부분 코멘트 남겼습니다.

2022-07-11 06:47 UTC, DWL21 commented on 2주차/11866/11866_python_제로.py
> +        break
if문 없이 가능하지 않을까요?

2022-07-11 06:47 UTC, DWL21 commented on 2주차/11866/11866_python_제로.py
> +    if visited[current] == False:
```suggestion
    if not visited[current]:
```
궁금하면 파이썬 pep-8 스타일 가이드의 Programming Recommendations 단락을 살펴보면 좋을 것 같네요.
https://peps.python.org/pep-0008/

2022-07-11 06:47 UTC, DWL21 commented on 2주차/12789/11866_python_제로.py
> +        for j in range(len(checkLst)): # 추가진영
```suggestion
        for _ in range(len(checkLst)): # 추가진영
```
iterable 객체를 반복문에서 사용할 때 변수가 사용되지 않으면 언더스코어로 나타내는 것도 좋다고 생각합니다.

2022-07-11 06:47 UTC, DWL21 commented on 2주차/12789/11866_python_제로.py
> +for i in range(len(checkLst) - 1):
`for i in range(len(list)):` 대신 `for index, value in enumerate(list):` 을 사용할 수도 있습니다.

2022-07-11 06:47 UTC, DWL21 commented on 2주차/22941/22941_python_제로.py
> +
이렇게 풀 수도 있군요 ㅎㅎ

2022-07-11 06:47 UTC, DWL21 commented on 2주차/22941/22941_python_제로.py
> +    if (1 <= bossHP <= p) and bossMoreChance == True:
파이썬에 적절한 코드로 개선가능한 부분이네요.

2022-07-11 11:30 UTC, DWL21 approved these changes
회식이라니 이해는 합니다만... 낼 확인하면 좋을 듯 합니다~ 수고하셨습니다

2022-07-11 11:30 UTC, DWL21 commented on 2주차/12789/12789_python_제로.py
> +    if index != len(checkLst) - 1 and checkLst[index] <= checkLst[index + 1]:
```suggestion
for index, value in enumerate(checkLst[:-1]):
    if value <= checkLst[index + 1]:
```
제가 의도했던 건 이런 식이었어요. 

근데 이 부분은 리스트 요소가 점점 작아지는 내림차순을 만족하면 통과하는거네요.
즉, 22-25 for문은 리스트가 내림차순이 아니면 break에 걸리니
저는 이 부분을 파이썬스럽게 짠다면 for문을 안 쓰고 이렇게 할 것 같네요. 참고하시면 좋을 듯 합니다~
```suggestion
if checkLst != sorted(check, reverse=True):
    answer = "Sad"
```

2022-07-11 11:40 UTC, DWL21 commented on 2주차/12789/12789_python_제로.py
> +    if index != len(checkLst) - 1 and checkLst[index] <= checkLst[index + 1]:
추가로 파이썬에서 슬라이싱 연산[:]은 범위를 넘어서도 상관없기 때문에 `[][:-1]` 도 예외가 발생하지 않아요.

2022-07-11 12:10 UTC, Juhyung990122 approved these changes
제로 고생많으셨어요~~

2022-07-11 12:10 UTC, Juhyung990122 commented on 2주차/11866/11866_python_제로.py
> +print(">")
문자열을 더해서 print함수를 한번만 출력해도 좋을 것 같아요!

2022-07-11 12:24 UTC, asebn1 commented on 2주차/12789/12789_python_제로.py
> +    if index != len(checkLst) - 1 and checkLst[index] <= checkLst[index + 1]:
아ㅋㅋㅋㅋㅇㅈ합니다

2022-07-12 05:47 UTC, merged