[아리] 1주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #9
Opened 2022-06-29 15:10 UTC by ulimy

부족한 실력이지만 잘부탁드립니다🙇🏻‍♀️

2022-06-29 15:16 UTC, kth990303 approved these changes
지나가다가 리뷰 남겨봤습니다ㅋㅋ
잘해주셔서 approve 남기고 갑니다!

2022-06-29 15:16 UTC, kth990303 commented on 1주차/14659/java_14659_아리.java
> +        for (int i = 0; i < count - 1; i++) {
필수적이진 않지만 따로 `count - 1`까지 빼신 점 좋네요

2022-06-29 15:16 UTC, kth990303 commented on 1주차/17362/java_17362_아리.java
> +        );
`map`으로 담는 건 생각도 못했네요!ㅋㅋㅋ
신박해서 보고 배워갑니다 :) 근데 map 자료구조가 조금 느리긴 할거예요 참고하시면 좋을 것 같습니다!

2022-06-29 15:16 UTC, kth990303 commented on 1주차/4796/java_4796_아리.java
> +        int result = V / P * L + Math.min(L, V % P);
깔끔하게 식 세워주셨네요 역시 아리 ㄷㄷ 👍

2022-06-30 11:30 UTC, yeongunheo requested changes
안녕하세요 아리!
전체적으로 깔끔하게 풀어주셔서 제가 따로 피드백 드릴건 없을 것 같아요 :)

[14659번 문제](https://www.acmicpc.net/problem/14659)의 경우 시간복잡도를 낮출 수 있는 다른 풀이가 존재하는데 부담되지 않는다면 좀 더 고민해보면 좋을 것 같아요!

2022-06-30 11:30 UTC, yeongunheo commented on 1주차/10814/java_10814_아리.java
> +        Collections.sort(list, Comparator.comparingInt(age -> Integer.parseInt(age.split(" ")[0])));
전 아래와 같이 class를 따로 만들어서 `Comparable`로 정렬을 처리했는데, 아리는 `Comparator` 방법을 사용해주셨네요!
간단한 정렬같은 경우엔 이 방법이 간결해서 좋은 것 같아요😀

```
class Member implements Comparable<Member> {
    private int age;
    private String name;

    // .. (생략)

    @Override
    public int compareTo(Member o) {
        return this.age - o.age;
    }
}
```

2022-06-30 11:30 UTC, yeongunheo commented on 1주차/14659/java_14659_아리.java
> +            result = Math.max(result, kill);
저도 처음에 아리처럼 이중 for문으로 이 문제를 해결했었는데요,
케이의 피드백을 받고 for문을 하나만 쓰는 방식으로 변경해 시간복잡도를 낮췄습니다!

부담스럽지 않다면 아리도 이부분을 한번 고민해보면 좋을 것 같아요!

2022-07-02 06:14 UTC, Seongwon97 approved these changes
안녕하세요 아리
스터디 초반이라 크게 피드백 드릴건 없었던 것 같아요

다만 참고할만한 몇몇 자료들을 첨부해봤어요~
다음주도 화이팅입니다😁

2022-07-02 06:14 UTC, Seongwon97 commented on 1주차/4796/java_4796_아리.java
> +        int result = V / P * L + Math.min(L, V % P);
와우...저는 저 식을 도출하기까지 6~7라인을 적었던거 같은데.. 식이 너무 깔끔하네요👍

2022-07-02 06:26 UTC, Seongwon97 commented on 1주차/10814/java_10814_아리.java
> +        }
출력 부분만 변경하여도 큰 차이가 날거에요!

![image](https://user-images.githubusercontent.com/57744251/176989301-5884d313-92cb-4982-a9ae-ca2ef8be37de.png)
- 맨 위: `BufferedWriter`사용
- 중간: 여러번의 `System.out.println()`을 통한 출력
- 맨 아래: `StringBuiler`를 사용해 문장을 완성 후 한번의 `System.out.println()`사용

2022-07-03 13:42 UTC, ulimy commented on 1주차/14659/java_14659_아리.java
> +        for (int i = 0; i < count - 1; i++) {
사소한 칭찬도 아끼지 않는 케이 너무 좋네요~

2022-07-03 13:42 UTC, ulimy commented on 1주차/14659/java_14659_아리.java
> +            result = Math.max(result, kill);
학습해서 수정해보았습니다!

2022-07-03 13:43 UTC, ulimy commented on 1주차/17362/java_17362_아리.java
> +        );
저도 map을 사용해도 되나 싶어 switch와 map 둘 다 해봤더니 소요시간이 똑같더라구요..! 아마 값이 몇개 없어서 그런가봅니다! 참고하겠습니당~

2022-07-03 13:44 UTC, ulimy commented on 1주차/4796/java_4796_아리.java
> +        int result = V / P * L + Math.min(L, V % P);
😝

2022-07-03 13:44 UTC, ulimy commented on 1주차/10814/java_10814_아리.java
> +        Collections.sort(list, Comparator.comparingInt(age -> Integer.parseInt(age.split(" ")[0])));
😃

2022-07-03 13:44 UTC, ulimy commented on 1주차/14659/java_14659_아리.java
> +            result = Math.max(result, kill);
학습해서 수정해보았습니다!

2022-07-03 13:44 UTC, ulimy commented on 1주차/10814/java_10814_아리.java
> +        }
크으 이렇게 자세한 리뷰라니....ㅠ 시작부터 감동이네요...ㅠㅠㅠㅠㅠㅠㅠㅠㅠ StringBuiler를 이용하도록 수정했습니다!

2022-07-03 13:45 UTC, ulimy commented on 1주차/10814/java_10814_아리.java
> +        Collections.sort(list, Comparator.comparingInt(age -> Integer.parseInt(age.split(" ")[0])));
자료 첨부까지..! 천사렉스 감사합니당^~^ 수정했습니다! 수정하고 다시 제출해보니 정말 많이 빨라졌어요!

2022-07-03 13:45 UTC, ulimy commented on 1주차/14659/java_14659_아리.java
> +                .toArray();
오 그런 생각은 못했네요.. 참고하겠습니다!

2022-07-03 13:46 UTC, ulimy commented on 1주차/4796/java_4796_아리.java
> +        int result = V / P * L + Math.min(L, V % P);
😊

2022-07-03 23:42 UTC, yeongunheo approved these changes
피드백 반영한 부분 확인했습니다!
이만 approve 할게요 :)

2022-07-04 16:54 UTC, merged