[페퍼] 3주차 과제 제출
woowacourse-study/2022-lv3-algorithm-study pull request #99
Opened 2022-07-16 12:54 UTC by SuyeonChoi

## 3주차 문제
- [x] [민균이의 계략](https://www.acmicpc.net/problem/11568)
- [ ] [배열 놀이](https://www.acmicpc.net/problem/17123)
- [ ] [이상한 술집](https://www.acmicpc.net/problem/13702)
- [x] [팰린드롬 만들기](https://www.acmicpc.net/problem/1254)

## 리뷰어님께!
제 팰린드롬 코드는 더티코드 그 자체입니다.. 하지만 코케인 코제로를 믿기에 리팩터링 없이 제출합니다🤪🤪
이상한 술집은 접근을 어떻게 해야할지 아예 감이 안오는데 훌륭하신 리뷰어분들께서 코멘트로 힌트를 주시길 바래봅니다,,🙏
시간이 난다면 배열 놀이도 풀어볼게요🔥

## 느낀점
민균이의 계략 덕분에 LIS 알고리즘을 알게되었둥〰️ 이번엔 DP처럼 풀었는데 다음에 이런 유형을 만난다면 이분 탐색으로도 풀어보겠둥〰️
다음주에는 시간관리를 잘해서 꼭 다 풀어보겠둥...😢

2022-07-17 18:11 UTC, asebn1 approved these changes
paper 이번에도 고생하셨습니다 ^-^ 👍

2022-07-17 18:11 UTC, asebn1 commented on 3주차/11568/11568_kotlin_페퍼.kt
> +    }
깔끔하게 LIS 구현하셨네요~
paper앞에선 민균이는 어림도 없군요?

2022-07-17 18:11 UTC, asebn1 commented on 3주차/1254/1254_kotlin_페퍼.kt
> +}
for문의 범위를 `0 until originStrLength`로 하면,
검증로직을 `reflectByNumber`, `reflect` 두 개로 나누지 않고 더 간단하게 해결할 수 있을 것 같아요!

2022-07-18 07:54 UTC, kth990303 requested changes
좀 더 개선해보면 좋은 문제가 하나 존재해서 RC 했습니다!

2022-07-18 07:54 UTC, kth990303 commented on 3주차/11568/11568_kotlin_페퍼.kt
> +    println(length.maxOrNull() ?: 1)
엘비스 연산자는 null 처리를 위함인가요?
엘비스 연산자가 없어도 통과할 것 같아서 궁금해서 여쭤봅니다!

2022-07-18 07:54 UTC, kth990303 commented on 3주차/1254/1254_kotlin_페퍼.kt
> +    println(answer)
조금 어렵게 푼 거 같아요.
아래 성질을 이용해서 좀 더 생각해볼까요?

1. 가장 작은 개수를 붙이기 위해선, 주어진 문자열의 문자들을 최대한 활용하는 것이 좋다.
2. 주어진 문자열을 최대한 활용하기 위해선, `str.substring(i, str.length()-1)`이 팰린드롬이면서 가장 긴 때를 찾으면 어떨까?

위 성질을 이용해서 훨씬 간편하게 처리할 수 있어보이며, 따로 문자열 길이가 1일 때 예외처리라든지, 문자열이 이미 팰린드롬일 때 예외처리 등이 필요 없게 할 수 있어보여요.

2022-07-18 07:54 UTC, kth990303 commented on 3주차/11568/11568_kotlin_페퍼.kt
> +    println(length.maxOrNull() ?: 1)
추가로, 이거 때문에 request changes는 아니어서 수정 안하셔도 돼요

2022-07-18 12:14 UTC, SuyeonChoi commented on 3주차/11568/11568_kotlin_페퍼.kt
> +    println(length.maxOrNull() ?: 1)
넵 맞습니다~! 그런데 `null` 나올일이 없어서 케이 말대로 통과하네요!!👍

2022-07-18 13:46 UTC, kth990303 approved these changes
수고하셨어요!

2022-07-18 13:46 UTC, kth990303 commented on 3주차/1254/1254_kotlin_페퍼.kt
> +    if (this == this.reversed())
`return this == this.reversed()`로 바로 리턴시킬 수 있겠네요!

2022-07-19 02:15 UTC, merged